name: BetterDispensers
main: me.exphc.BetterDispensers.BetterDispensers
version: 1.1
commands:
    dispenser:
        description: Change or view dispenser information
        usage: /<command> [direction]
        aliases: disp
permissions:
    betterdispensers.*:
        children:
            betterdispensers.command: true
        default: false
    betterdispensers.command:
        description: Allows you to use the /dispenser command
        default: op
