name: BetterDispensers
main: me.exphc.BetterDispensers.BetterDispensers
version: 0.2
commands:
    dispenser:
        description: Change or view dispenser information
        usage: /<command> [direction]
        aliases: disp
